[package]
name = "userphone"
version = "0.1.0"
edition = "2024"

[dependencies]
colorful = "0.3.2"
dashmap = "6.1.0"
dotenv = "0.15.0"
parking_lot = "0.12.3"
poise = "0.6.1"
tokio = { version = "1.44.2", features=["rt-multi-thread"] }
